[package]
name = "rand"
version = "0.2.0"
license = "AGPL-3.0"
authors = ["Simon Warta <simon@confio.tech>"]
edition = "2018"
resolver = "2"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta6" }
cosmwasm-storage = { version = "1.0.0-beta6" }
drand-verify = "0.1"
cw2 = "0.13"
schemars = "0.8.3"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0"
rand_xoshiro = { version = "0.6.0", default-features = false }
rand_core = { version = "0.6", default-features = false }
shuffle = { git = "https://github.com/webmaster128/shuffle", branch = "rm-getrandom" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta6" }
cosmwasm-vm = { version = "1.0.0-beta6" }
hex = "0.4"
